from app.utils.model_prediction.make_prediction import initialize_model
from app.utils.database_helper_functions import create_cosmos_db_client
from app.utils.startup.process_project_metadata import process_project_metadata
